/**
 * SusWord — Full word pair pool (150 pairs)
 * Each pair: { mainWord, imposterWord, category }
 * Main word → civilians | Imposter word → similar but different
 */

const WORD_PAIRS = [
  // ── Animals ──────────────────────────────────────────────
  { mainWord: 'Dolphin',    imposterWord: 'Whale',       category: 'Animals' },
  { mainWord: 'Wolf',       imposterWord: 'Fox',         category: 'Animals' },
  { mainWord: 'Eagle',      imposterWord: 'Hawk',        category: 'Animals' },
  { mainWord: 'Frog',       imposterWord: 'Toad',        category: 'Animals' },
  { mainWord: 'Alligator',  imposterWord: 'Crocodile',   category: 'Animals' },
  { mainWord: 'Turtle',     imposterWord: 'Tortoise',    category: 'Animals' },
  { mainWord: 'Rabbit',     imposterWord: 'Hare',        category: 'Animals' },
  { mainWord: 'Leopard',    imposterWord: 'Cheetah',     category: 'Animals' },
  { mainWord: 'Bison',      imposterWord: 'Buffalo',     category: 'Animals' },
  { mainWord: 'Donkey',     imposterWord: 'Mule',        category: 'Animals' },
  { mainWord: 'Crow',       imposterWord: 'Raven',       category: 'Animals' },
  { mainWord: 'Sparrow',    imposterWord: 'Finch',       category: 'Animals' },
  { mainWord: 'Seal',       imposterWord: 'Sea Lion',    category: 'Animals' },
  { mainWord: 'Shrimp',     imposterWord: 'Prawn',       category: 'Animals' },
  { mainWord: 'Moth',       imposterWord: 'Butterfly',   category: 'Animals' },
  { mainWord: 'Llama',      imposterWord: 'Alpaca',      category: 'Animals' },
  { mainWord: 'Caterpillar',imposterWord: 'Larva',       category: 'Animals' },
  { mainWord: 'Pigeon',     imposterWord: 'Dove',        category: 'Animals' },
  { mainWord: 'Panther',    imposterWord: 'Jaguar',      category: 'Animals' },
  { mainWord: 'Otter',      imposterWord: 'Beaver',      category: 'Animals' },

  // ── Food & Drink ──────────────────────────────────────────
  { mainWord: 'Pancake',    imposterWord: 'Waffle',      category: 'Food' },
  { mainWord: 'Butter',     imposterWord: 'Margarine',   category: 'Food' },
  { mainWord: 'Sushi',      imposterWord: 'Sashimi',     category: 'Food' },
  { mainWord: 'Cupcake',    imposterWord: 'Muffin',      category: 'Food' },
  { mainWord: 'Coffee',     imposterWord: 'Espresso',    category: 'Food' },
  { mainWord: 'Jam',        imposterWord: 'Jelly',       category: 'Food' },
  { mainWord: 'Soup',       imposterWord: 'Stew',        category: 'Food' },
  { mainWord: 'Pizza',      imposterWord: 'Flatbread',   category: 'Food' },
  { mainWord: 'Mango',      imposterWord: 'Papaya',      category: 'Food' },
  { mainWord: 'Donut',      imposterWord: 'Bagel',       category: 'Food' },
  { mainWord: 'Biscuit',    imposterWord: 'Cracker',     category: 'Food' },
  { mainWord: 'Milkshake',  imposterWord: 'Smoothie',    category: 'Food' },
  { mainWord: 'Noodle',     imposterWord: 'Pasta',       category: 'Food' },
  { mainWord: 'Taco',       imposterWord: 'Burrito',     category: 'Food' },
  { mainWord: 'Cake',       imposterWord: 'Pie',         category: 'Food' },
  { mainWord: 'Popcorn',    imposterWord: 'Puffed Rice', category: 'Food' },
  { mainWord: 'Lemonade',   imposterWord: 'Limeade',     category: 'Food' },
  { mainWord: 'Cereal',     imposterWord: 'Granola',     category: 'Food' },
  { mainWord: 'Lasagna',    imposterWord: 'Moussaka',    category: 'Food' },
  { mainWord: 'Pretzel',    imposterWord: 'Breadstick',  category: 'Food' },

  // ── Places ────────────────────────────────────────────────
  { mainWord: 'Beach',      imposterWord: 'Desert',      category: 'Places' },
  { mainWord: 'Library',    imposterWord: 'Bookstore',   category: 'Places' },
  { mainWord: 'Hotel',      imposterWord: 'Motel',       category: 'Places' },
  { mainWord: 'Castle',     imposterWord: 'Palace',      category: 'Places' },
  { mainWord: 'Lake',       imposterWord: 'Pond',        category: 'Places' },
  { mainWord: 'Museum',     imposterWord: 'Gallery',     category: 'Places' },
  { mainWord: 'Cinema',     imposterWord: 'Theatre',     category: 'Places' },
  { mainWord: 'Temple',     imposterWord: 'Shrine',      category: 'Places' },
  { mainWord: 'Clinic',     imposterWord: 'Hospital',    category: 'Places' },
  { mainWord: 'Supermarket',imposterWord: 'Grocery',     category: 'Places' },
  { mainWord: 'Gym',        imposterWord: 'Studio',      category: 'Places' },
  { mainWord: 'Lighthouse', imposterWord: 'Watchtower',  category: 'Places' },
  { mainWord: 'Meadow',     imposterWord: 'Prairie',     category: 'Places' },
  { mainWord: 'Swamp',      imposterWord: 'Marsh',       category: 'Places' },
  { mainWord: 'Volcano',    imposterWord: 'Geyser',      category: 'Places' },

  // ── Objects ───────────────────────────────────────────────
  { mainWord: 'Guitar',     imposterWord: 'Ukulele',     category: 'Objects' },
  { mainWord: 'Couch',      imposterWord: 'Sofa',        category: 'Objects' },
  { mainWord: 'Sword',      imposterWord: 'Dagger',      category: 'Objects' },
  { mainWord: 'Clock',      imposterWord: 'Watch',       category: 'Objects' },
  { mainWord: 'Pillow',     imposterWord: 'Cushion',     category: 'Objects' },
  { mainWord: 'Lamp',       imposterWord: 'Lantern',     category: 'Objects' },
  { mainWord: 'Mirror',     imposterWord: 'Window',      category: 'Objects' },
  { mainWord: 'Rifle',      imposterWord: 'Shotgun',     category: 'Objects' },
  { mainWord: 'Pen',        imposterWord: 'Pencil',      category: 'Objects' },
  { mainWord: 'Mug',        imposterWord: 'Cup',         category: 'Objects' },
  { mainWord: 'Bucket',     imposterWord: 'Pail',        category: 'Objects' },
  { mainWord: 'Ladder',     imposterWord: 'Staircase',   category: 'Objects' },
  { mainWord: 'Telescope',  imposterWord: 'Binoculars',  category: 'Objects' },
  { mainWord: 'Violin',     imposterWord: 'Cello',       category: 'Objects' },
  { mainWord: 'Trumpet',    imposterWord: 'Trombone',    category: 'Objects' },
  { mainWord: 'Microscope', imposterWord: 'Magnifier',   category: 'Objects' },
  { mainWord: 'Thermos',    imposterWord: 'Flask',       category: 'Objects' },
  { mainWord: 'Compass',    imposterWord: 'Protractor',  category: 'Objects' },
  { mainWord: 'Hammock',    imposterWord: 'Swing',       category: 'Objects' },
  { mainWord: 'Gloves',     imposterWord: 'Mittens',     category: 'Objects' },

  // ── Activities ────────────────────────────────────────────
  { mainWord: 'Swimming',   imposterWord: 'Diving',      category: 'Activities' },
  { mainWord: 'Painting',   imposterWord: 'Drawing',     category: 'Activities' },
  { mainWord: 'Jogging',    imposterWord: 'Sprinting',   category: 'Activities' },
  { mainWord: 'Camping',    imposterWord: 'Hiking',      category: 'Activities' },
  { mainWord: 'Singing',    imposterWord: 'Humming',     category: 'Activities' },
  { mainWord: 'Knitting',   imposterWord: 'Crocheting',  category: 'Activities' },
  { mainWord: 'Surfing',    imposterWord: 'Wakeboarding',category: 'Activities' },
  { mainWord: 'Boxing',     imposterWord: 'Wrestling',   category: 'Activities' },
  { mainWord: 'Skiing',     imposterWord: 'Snowboarding',category: 'Activities' },
  { mainWord: 'Gardening',  imposterWord: 'Farming',     category: 'Activities' },
  { mainWord: 'Baking',     imposterWord: 'Cooking',     category: 'Activities' },
  { mainWord: 'Cycling',    imposterWord: 'Skating',     category: 'Activities' },
  { mainWord: 'Fishing',    imposterWord: 'Hunting',     category: 'Activities' },
  { mainWord: 'Meditation', imposterWord: 'Yoga',        category: 'Activities' },
  { mainWord: 'Photography',imposterWord: 'Videography', category: 'Activities' },

  // ── Clothing ──────────────────────────────────────────────
  { mainWord: 'Jacket',     imposterWord: 'Coat',        category: 'Clothing' },
  { mainWord: 'Sandals',    imposterWord: 'Slippers',    category: 'Clothing' },
  { mainWord: 'Cap',        imposterWord: 'Hat',         category: 'Clothing' },
  { mainWord: 'Scarf',      imposterWord: 'Shawl',       category: 'Clothing' },
  { mainWord: 'Shirt',      imposterWord: 'Blouse',      category: 'Clothing' },
  { mainWord: 'Trousers',   imposterWord: 'Leggings',    category: 'Clothing' },
  { mainWord: 'Sneakers',   imposterWord: 'Trainers',    category: 'Clothing' },
  { mainWord: 'Hoodie',     imposterWord: 'Sweatshirt',  category: 'Clothing' },
  { mainWord: 'Overalls',   imposterWord: 'Dungarees',   category: 'Clothing' },
  { mainWord: 'Raincoat',   imposterWord: 'Windbreaker', category: 'Clothing' },

  // ── Nature ────────────────────────────────────────────────
  { mainWord: 'Thunder',    imposterWord: 'Lightning',   category: 'Nature' },
  { mainWord: 'Hill',       imposterWord: 'Mountain',    category: 'Nature' },
  { mainWord: 'River',      imposterWord: 'Stream',      category: 'Nature' },
  { mainWord: 'Fog',        imposterWord: 'Mist',        category: 'Nature' },
  { mainWord: 'Sunset',     imposterWord: 'Sunrise',     category: 'Nature' },
  { mainWord: 'Tornado',    imposterWord: 'Cyclone',     category: 'Nature' },
  { mainWord: 'Glacier',    imposterWord: 'Iceberg',     category: 'Nature' },
  { mainWord: 'Coral',      imposterWord: 'Reef',        category: 'Nature' },
  { mainWord: 'Dune',       imposterWord: 'Sandbar',     category: 'Nature' },
  { mainWord: 'Avalanche',  imposterWord: 'Landslide',   category: 'Nature' },

  // ── Jobs & People ─────────────────────────────────────────
  { mainWord: 'Doctor',     imposterWord: 'Nurse',       category: 'Jobs' },
  { mainWord: 'Teacher',    imposterWord: 'Tutor',       category: 'Jobs' },
  { mainWord: 'Pilot',      imposterWord: 'Astronaut',   category: 'Jobs' },
  { mainWord: 'Chef',       imposterWord: 'Baker',       category: 'Jobs' },
  { mainWord: 'Lawyer',     imposterWord: 'Judge',       category: 'Jobs' },
  { mainWord: 'Architect',  imposterWord: 'Engineer',    category: 'Jobs' },
  { mainWord: 'Journalist', imposterWord: 'Reporter',    category: 'Jobs' },
  { mainWord: 'Sailor',     imposterWord: 'Soldier',     category: 'Jobs' },
  { mainWord: 'Barber',     imposterWord: 'Hairdresser', category: 'Jobs' },
  { mainWord: 'Plumber',    imposterWord: 'Electrician', category: 'Jobs' },

  // ── Transport ─────────────────────────────────────────────
  { mainWord: 'Helicopter', imposterWord: 'Aeroplane',   category: 'Transport' },
  { mainWord: 'Submarine',  imposterWord: 'Yacht',       category: 'Transport' },
  { mainWord: 'Tram',       imposterWord: 'Subway',      category: 'Transport' },
  { mainWord: 'Scooter',    imposterWord: 'Moped',       category: 'Transport' },
  { mainWord: 'Canoe',      imposterWord: 'Kayak',       category: 'Transport' },
  { mainWord: 'Bulldozer',  imposterWord: 'Excavator',   category: 'Transport' },
  { mainWord: 'Carriage',   imposterWord: 'Chariot',     category: 'Transport' },
  { mainWord: 'Ferry',      imposterWord: 'Cruise Ship', category: 'Transport' },

  // ── Tech ──────────────────────────────────────────────────
  { mainWord: 'Laptop',     imposterWord: 'Tablet',      category: 'Tech' },
  { mainWord: 'Keyboard',   imposterWord: 'Keypad',      category: 'Tech' },
  { mainWord: 'Router',     imposterWord: 'Modem',       category: 'Tech' },
  { mainWord: 'Printer',    imposterWord: 'Scanner',     category: 'Tech' },
  { mainWord: 'Headphones', imposterWord: 'Earbuds',     category: 'Tech' },
  { mainWord: 'Drone',      imposterWord: 'Remote Car',  category: 'Tech' },
  { mainWord: 'Smartwatch', imposterWord: 'Fitness Band',category: 'Tech' },
]

module.exports = { WORD_PAIRS }
